spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brainflash
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
